package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Car;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    Car selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    List<Car> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int updateByPrimaryKey(Car record);

    // added manually

    List<Car> selectAllByCarOwner(Integer carOwnerId);
}