package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.CarPart;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int insert(CarPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    CarPart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    List<CarPart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    int updateByPrimaryKey(CarPart record);
}