package lt.vu.mybatis.model;

public class CarOwner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAROWNER.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAROWNER.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAROWNER.PHONENUMBER
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAROWNER.SURNAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAROWNER.ID
     *
     * @return the value of PUBLIC.CAROWNER.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAROWNER.ID
     *
     * @param id the value for PUBLIC.CAROWNER.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAROWNER.NAME
     *
     * @return the value of PUBLIC.CAROWNER.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAROWNER.NAME
     *
     * @param name the value for PUBLIC.CAROWNER.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAROWNER.PHONENUMBER
     *
     * @return the value of PUBLIC.CAROWNER.PHONENUMBER
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAROWNER.PHONENUMBER
     *
     * @param phoneNumber the value for PUBLIC.CAROWNER.PHONENUMBER
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAROWNER.SURNAME
     *
     * @return the value of PUBLIC.CAROWNER.SURNAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAROWNER.SURNAME
     *
     * @param surname the value for PUBLIC.CAROWNER.SURNAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}