package lt.vu.mybatis.model;

public class CarPartCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARPART_CAR.CAR_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARPART_CAR.CARPART_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private Integer carPartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARPART_CAR.CAR_ID
     *
     * @return the value of PUBLIC.CARPART_CAR.CAR_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARPART_CAR.CAR_ID
     *
     * @param carId the value for PUBLIC.CARPART_CAR.CAR_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARPART_CAR.CARPART_ID
     *
     * @return the value of PUBLIC.CARPART_CAR.CARPART_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public Integer getCarPartId() {
        return carPartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARPART_CAR.CARPART_ID
     *
     * @param carPartId the value for PUBLIC.CARPART_CAR.CARPART_ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setCarPartId(Integer carPartId) {
        this.carPartId = carPartId;
    }
}