package lt.vu.mybatis.model;

import java.util.List;

public class CarPart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARPART.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARPART.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARPART.ID
     *
     * @return the value of PUBLIC.CARPART.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARPART.ID
     *
     * @param id the value for PUBLIC.CARPART.ID
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARPART.NAME
     *
     * @return the value of PUBLIC.CARPART.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARPART.NAME
     *
     * @param name the value for PUBLIC.CARPART.NAME
     *
     * @mbg.generated Fri Apr 12 21:42:49 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    // added manually

    private List<Car> cars;

    public List<Car> getCars() { return cars; }

    public void setCars(List<Car> cars) { this.cars = cars; }
}